blueprint:
  css:
    base:
      //fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&family=PT+Serif:wght@400;700&display=swap: { type: external, minified: true }
    theme:
      css/variables.css: { weight: -10 }
      css/layout.css: { weight: -9 }
      css/components.css: { weight: -8 }
      css/add-ons.css: { weight: -7 }
  js:
    js/back-button.js: {}
  dependencies:
    - core/once

progress:
  js:
    js/progress.js: {}
  dependencies:
    - core/drupal
